export const SITE_ROUTES = [
  {
    path: "/",
    title: "Home",
    description: "Discover latest deals, new arrivals, and products picked for you.",
    changefreq: "daily",
    priority: 1,
  },
  {
    path: "/products",
    title: "Products",
    description: "Browse Sam Global products with category, delivery, and pricing features.",
    changefreq: "daily",
    priority: 0.9,
  },
  {
    path: "/search",
    title: "Search Products",
    description: "Search products across Sam Global categories.",
    changefreq: "daily",
    priority: 0.8,
  },
  {
    path: "/deals",
    title: "Deals",
    description: "Fresh Sam Global deals across shopping categories.",
    changefreq: "daily",
    priority: 0.8,
  },
  {
    path: "/brand-outlet",
    title: "Brand Outlet",
    description: "Premium brands and outlet offers at smarter prices.",
    changefreq: "daily",
    priority: 0.7,
  },
  {
    path: "/gift-cards",
    title: "Gift Cards",
    description: "Flexible Sam Global gift card options for every occasion.",
    changefreq: "monthly",
    priority: 0.6,
  },
  {
    path: "/help-contact",
    title: "Help & Contact",
    description: "Get support for orders, returns, payments, and account questions.",
    changefreq: "weekly",
    priority: 0.6,
  },
  {
    path: "/who-we-are",
    title: "Who We Are",
    description: "Learn about Sam Global's shopping platform and values.",
    changefreq: "monthly",
    priority: 0.5,
  },
  {
    path: "/mobile-app",
    title: "Mobile App",
    description: "Shop faster with Sam Global mobile app features.",
    changefreq: "monthly",
    priority: 0.5,
  },
  {
    path: "/seller-policies",
    title: "Seller Policies",
    description: "Marketplace standards and policies for Sam Global sellers.",
    changefreq: "monthly",
    priority: 0.4,
  },
  {
    path: "/growth-support",
    title: "Growth Support",
    description: "Growth support for Sam Global sellers, brands, and retail partners.",
    changefreq: "monthly",
    priority: 0.4,
  },
  {
    path: "/advertise",
    title: "Advertise",
    description: "Advertising options for brands and sellers on Sam Global.",
    changefreq: "monthly",
    priority: 0.4,
  },
  {
    path: "/blog",
    title: "Blog",
    description: "Shopping guides, marketplace stories, and product inspiration.",
    changefreq: "weekly",
    priority: 0.5,
  },
  {
    path: "/updates",
    title: "Updates",
    description: "Product, policy, marketplace, and shopping campaign updates.",
    changefreq: "weekly",
    priority: 0.4,
  },
  {
    path: "/announcements",
    title: "Announcements",
    description: "Official Sam Global notices for customers, sellers, and partners.",
    changefreq: "weekly",
    priority: 0.4,
  },
  {
    path: "/cart",
    title: "Cart",
    description: "Review your cart and continue checkout.",
    changefreq: "weekly",
    priority: 0.3,
    robots: "noindex,nofollow",
    includeInSitemap: false,
  },
  {
    path: "/account/profile",
    title: "Account",
    description: "Manage your Sam Global account profile.",
    changefreq: "monthly",
    priority: 0.2,
    robots: "noindex,nofollow",
    includeInSitemap: false,
  },
  {
    path: "/orders",
    title: "Orders",
    description: "View and track your Sam Global orders.",
    changefreq: "weekly",
    priority: 0.2,
    robots: "noindex,nofollow",
    includeInSitemap: false,
  },
  {
    path: "/seller/status",
    title: "Seller Status",
    description: "Check seller onboarding and web status.",
    changefreq: "monthly",
    priority: 0.2,
    robots: "noindex,nofollow",
    includeInSitemap: false,
  },
];

export const DYNAMIC_ROUTE_PATTERNS = [
  {
    path: "/products/:productId",
    entity: "product",
    changefreq: "daily",
    priority: 0.8,
  },
  {
    path: "/categories/:categoryKey",
    entity: "category",
    changefreq: "daily",
    priority: 0.7,
  },
  {
    path: "/cms/:slug",
    entity: "cms",
    changefreq: "weekly",
    priority: 0.5,
  },
];
