export const REGEX = Object.freeze({
  email: /^(?!.*\.\.)[A-Z0-9._%+-]+@[A-Z0-9-]+(?:\.[A-Z0-9-]+)+$/i,
  phone: /^\d{10}$/,
  passwordUppercase: /[A-Z]/,
  passwordLowercase: /[a-z]/,
  passwordNumber: /\d/,
  passwordSpecial: /[^A-Za-z0-9]/,
  otp: /^\d{6}$/,
  postalCode: /^[A-Za-z0-9][A-Za-z0-9\s-]{2,11}$/,
  // Relaxed: allow any digit sequence and let the API enforce exact PIN requirements
  indianPostalCode: /^\d+$/,
  lettersOnly: /^[A-Za-z]+$/,
  name: /^[A-Za-z]+(?:[ '.-][A-Za-z]+)*$/,
  safeText: /^[A-Za-z0-9\s.,'’"()/&:+#-]+$/,
  addressLine: /^[A-Za-z0-9\s.,'’/#()-]+$/,
  slug: /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
  sku: /^[A-Z0-9][A-Z0-9_-]{2,39}$/,
  couponCode: /^[A-Z0-9][A-Z0-9_-]{2,29}$/,
  pan: /^[A-Z]{5}[0-9]{4}[A-Z]$/,
  aadhaar: /^\d{12}$/,
  url: /^https?:\/\/.+/i,
});
